FROM ubuntu:23.10



#set root passwd
RUN echo 'root:root' | chpasswd
RUN printf '#!/bin/sh\nexit 0' > /usr/sbin/policy-rc.d


#set user
# define a USER
# Environment variables for user
ENV PUID='1001'
ENV PGID='1001'
ENV USER='user'

# create user $USER
RUN groupadd --gid "$PGID" "$USER" 
RUN useradd --home-dir /home/$USER --shell /bin/bash --uid "$PUID" --gid "$PGID" "$USER" 
# RUN echo $USER | passwd --stdin $USER
RUN mkdir /home/$USER && chown -R $USER:$USER /home/$USER 
# add $USER to sudo
RUN mkdir -p /etc/sudoers.d 
RUN echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/"$USER" \
    && chmod 0440 /etc/sudoers.d/"$USER"

# install dbus
RUN apt-get update
RUN apt-get install -y systemd systemd-sysv dbus dbus-user-session

# x downlaods
RUN apt-get update && apt-get install -yqq xvfb \
    adduser \
    x11vnc \
    bash \
    vim \
    htop \
    sudo \
    fluxbox \
    x11-utils # for xdpyinfo \
    bash \
    vim \
    terminus-font \
    curl \
    wget \
    ca-certificates \
    unzip 
    
    # Chrome dependency Instalation \
    # FROM HERE - https://github.com/Dmitry-Ostashev/testcafe-kubernetes-example/blob/main/Dockerfile \
    RUN apt-get update && apt-get install -yqq fonts-liberation \
    libasound2 \
    libatk-bridge2.0-0 \
    libatk1.0-0 \
    libatspi2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libnspr4 \
    libnss3 \
    libwayland-client0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxkbcommon0 \
    libxrandr2 \
    xdg-utils \
    libu2f-udev \
    libvulkan1 \
    gcc
# for chrome FROM HERE
# https://stackoverflow.com/questions/71571296/can-i-silence-qstandardpaths-xdg-runtime-dir-not-set-defaulting-to-tmp-runti
ENV XDG_RUNTIME_DIR=/tmp

# download google-chrome
# RUN echo $?
# RUN cd /tmp && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
# RUN curl -vsSLO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

ADD download/google-chrome-stable_current_amd64.deb .


# install google-chrome
RUN apt-get install -yqq ./google-chrome-stable_current_amd64.deb

#start systemd
RUN printf "systemctl start systemd-logind" >> /etc/profile


# clean up
RUN apt-get autoremove -y \
    && apt-get clean -y \
    && apt-get autoclean -y \
    && rm -rf /var/lib/apt/lists/*


# copy bootstrap.sh
RUN mkdir -p /opt
COPY /bootstrap.sh /opt
# run 
CMD ["/bin/bash","/opt/bootstrap.sh"]


# ENTRYPOINT ["/sbin/init"]


# hier weiter 

# cd systemd
# docker build -t ubuntu_23_10_xvfb -f Dockerfile_ubuntu_23_10_xvfb "."

# run
# docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -v /var/run/dbus:/var/run/dbus -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN --security-opt apparmor=unconfined --tmpfs /run ubuntu_23_10_xvfb

# docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -v /var/run/dbus:/var/run/dbus -v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket  -v /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN --security-opt apparmor=unconfined --tmpfs /run ubuntu_23_10_xvfb

